/**
 * Thai alphabet — all 44 consonants in traditional dictionary order,
 * plus the core vowel inventory.
 *
 * Romanization is Paiboon-style (g/k, j/ch, d/dt, b/bp, ɛ, ɔ, ə, ɯ),
 * with tone diacritics on acrophonic names and example words.
 */
import type { ThaiConsonant, ThaiVowel } from "../schema"

// ─────────────────────────────── Consonants ──────────────────────────────────
// class: mid (9) / high (11) / low (24). freq: 1 very common, 2 common, 3 rare.
// final '' = never used in syllable-final position (ฃ ฅ are fully obsolete).

export const consonants: ThaiConsonant[] = [
  { char: "ก", name: "gɔɔ gài", meaning: "chicken", emoji: "🐔", class: "mid", initial: "g", final: "k", freq: 1 },
  { char: "ข", name: "kɔ̌ɔ kài", meaning: "egg", emoji: "🥚", class: "high", initial: "k", final: "k", freq: 1 },
  { char: "ฃ", name: "kɔ̌ɔ kùuat", meaning: "bottle (obsolete)", emoji: "🍾", class: "high", initial: "k", final: "", freq: 3 },
  { char: "ค", name: "kɔɔ kwaai", meaning: "water buffalo", emoji: "🐃", class: "low", initial: "k", final: "k", freq: 1 },
  { char: "ฅ", name: "kɔɔ kon", meaning: "person (obsolete)", emoji: "🧍", class: "low", initial: "k", final: "", freq: 3 },
  { char: "ฆ", name: "kɔɔ rá-kang", meaning: "bell", emoji: "🔔", class: "low", initial: "k", final: "k", freq: 3 },
  { char: "ง", name: "ngɔɔ nguu", meaning: "snake", emoji: "🐍", class: "low", initial: "ng", final: "ng", freq: 1 },
  { char: "จ", name: "jɔɔ jaan", meaning: "plate", emoji: "🍽️", class: "mid", initial: "j", final: "t", freq: 1 },
  { char: "ฉ", name: "chɔ̌ɔ chìng", meaning: "small cymbals", emoji: "🥁", class: "high", initial: "ch", final: "", freq: 2 },
  { char: "ช", name: "chɔɔ cháang", meaning: "elephant", emoji: "🐘", class: "low", initial: "ch", final: "t", freq: 1 },
  { char: "ซ", name: "sɔɔ sôo", meaning: "chain", emoji: "⛓️", class: "low", initial: "s", final: "t", freq: 2 },
  { char: "ฌ", name: "chɔɔ chəə", meaning: "tree", emoji: "🌳", class: "low", initial: "ch", final: "", freq: 3 },
  { char: "ญ", name: "yɔɔ yǐng", meaning: "woman", emoji: "👩", class: "low", initial: "y", final: "n", freq: 3 },
  { char: "ฎ", name: "dɔɔ chá-daa", meaning: "dancer's headdress", emoji: "👑", class: "mid", initial: "d", final: "t", freq: 3 },
  { char: "ฏ", name: "dtɔɔ bpà-dtàk", meaning: "goad, spear", emoji: "🗡️", class: "mid", initial: "dt", final: "t", freq: 3 },
  { char: "ฐ", name: "tɔ̌ɔ tǎan", meaning: "pedestal, base", emoji: "🏛️", class: "high", initial: "t", final: "t", freq: 3 },
  { char: "ฑ", name: "tɔɔ mon-too", meaning: "Montho (Ramakien queen)", emoji: "👸", class: "low", initial: "t", final: "t", freq: 3 },
  { char: "ฒ", name: "tɔɔ pûu-tâo", meaning: "elder", emoji: "👴", class: "low", initial: "t", final: "t", freq: 3 },
  { char: "ณ", name: "nɔɔ neen", meaning: "novice monk", emoji: "🧘", class: "low", initial: "n", final: "n", freq: 3 },
  { char: "ด", name: "dɔɔ dèk", meaning: "child", emoji: "👶", class: "mid", initial: "d", final: "t", freq: 1 },
  { char: "ต", name: "dtɔɔ dtào", meaning: "turtle", emoji: "🐢", class: "mid", initial: "dt", final: "t", freq: 1 },
  { char: "ถ", name: "tɔ̌ɔ tǔng", meaning: "sack, bag", emoji: "🛍️", class: "high", initial: "t", final: "t", freq: 2 },
  { char: "ท", name: "tɔɔ tá-hǎan", meaning: "soldier", emoji: "💂", class: "low", initial: "t", final: "t", freq: 1 },
  { char: "ธ", name: "tɔɔ tong", meaning: "flag", emoji: "🚩", class: "low", initial: "t", final: "t", freq: 3 },
  { char: "น", name: "nɔɔ nǔu", meaning: "mouse", emoji: "🐭", class: "low", initial: "n", final: "n", freq: 1 },
  { char: "บ", name: "bɔɔ bai-máai", meaning: "leaf", emoji: "🍃", class: "mid", initial: "b", final: "p", freq: 1 },
  { char: "ป", name: "bpɔɔ bplaa", meaning: "fish", emoji: "🐟", class: "mid", initial: "bp", final: "p", freq: 1 },
  { char: "ผ", name: "pɔ̌ɔ pɯ̂ng", meaning: "bee", emoji: "🐝", class: "high", initial: "p", final: "", freq: 2 },
  { char: "ฝ", name: "fɔ̌ɔ fǎa", meaning: "lid", emoji: "🫙", class: "high", initial: "f", final: "", freq: 2 },
  { char: "พ", name: "pɔɔ paan", meaning: "pedestal tray", emoji: "🏺", class: "low", initial: "p", final: "p", freq: 1 },
  { char: "ฟ", name: "fɔɔ fan", meaning: "teeth", emoji: "🦷", class: "low", initial: "f", final: "p", freq: 1 },
  { char: "ภ", name: "pɔɔ sǎm-pao", meaning: "sailing junk", emoji: "⛵", class: "low", initial: "p", final: "p", freq: 3 },
  { char: "ม", name: "mɔɔ máa", meaning: "horse", emoji: "🐴", class: "low", initial: "m", final: "m", freq: 1 },
  { char: "ย", name: "yɔɔ yák", meaning: "giant, ogre", emoji: "👹", class: "low", initial: "y", final: "i", freq: 1 },
  { char: "ร", name: "rɔɔ rɯa", meaning: "boat", emoji: "🛶", class: "low", initial: "r", final: "n", freq: 1 },
  { char: "ล", name: "lɔɔ ling", meaning: "monkey", emoji: "🐵", class: "low", initial: "l", final: "n", freq: 1 },
  { char: "ว", name: "wɔɔ wɛ̌ɛn", meaning: "ring", emoji: "💍", class: "low", initial: "w", final: "o", freq: 1 },
  { char: "ศ", name: "sɔ̌ɔ sǎa-laa", meaning: "pavilion", emoji: "🏯", class: "high", initial: "s", final: "t", freq: 2 },
  { char: "ษ", name: "sɔ̌ɔ rɯɯ-sǐi", meaning: "hermit", emoji: "🧙", class: "high", initial: "s", final: "t", freq: 2 },
  { char: "ส", name: "sɔ̌ɔ sɯ̌a", meaning: "tiger", emoji: "🐯", class: "high", initial: "s", final: "t", freq: 1 },
  { char: "ห", name: "hɔ̌ɔ hìip", meaning: "chest, box", emoji: "📦", class: "high", initial: "h", final: "", freq: 1 },
  { char: "ฬ", name: "lɔɔ jù-laa", meaning: "kite", emoji: "🪁", class: "low", initial: "l", final: "n", freq: 3 },
  { char: "อ", name: "ɔɔ àang", meaning: "basin", emoji: "🥣", class: "mid", initial: "", final: "", freq: 1 },
  { char: "ฮ", name: "hɔɔ nók-hûuk", meaning: "owl", emoji: "🦉", class: "low", initial: "h", final: "", freq: 2 },
]

// ──────────────────────────────── Vowels ─────────────────────────────────────
// display uses อ as the carrier consonant. Example romans carry tone marks.

export const vowels: ThaiVowel[] = [
  {
    id: "v.a",
    display: "อะ",
    roman: "a",
    length: "short",
    position: "after",
    example: { thai: "จะ", roman: "jà", en: "will (future)", emoji: "⏳" },
  },
  {
    id: "v.aa",
    display: "อา",
    roman: "aa",
    length: "long",
    position: "after",
    example: { thai: "มา", roman: "maa", en: "come", emoji: "🚶" },
  },
  {
    id: "v.i",
    display: "อิ",
    roman: "i",
    length: "short",
    position: "above",
    example: { thai: "สิบ", roman: "sìp", en: "ten", emoji: "🔟" },
  },
  {
    id: "v.ii",
    display: "อี",
    roman: "ii",
    length: "long",
    position: "above",
    example: { thai: "ดี", roman: "dii", en: "good", emoji: "👍" },
  },
  {
    id: "v.ue",
    display: "อึ",
    roman: "ɯ",
    length: "short",
    position: "above",
    example: { thai: "หนึ่ง", roman: "nɯ̀ng", en: "one", emoji: "1️⃣" },
  },
  {
    id: "v.uee",
    display: "อือ",
    roman: "ɯɯ",
    length: "long",
    position: "around",
    example: { thai: "มือ", roman: "mɯɯ", en: "hand", emoji: "✋" },
  },
  {
    id: "v.u",
    display: "อุ",
    roman: "u",
    length: "short",
    position: "below",
    example: { thai: "สุข", roman: "sùk", en: "happiness", emoji: "😊" },
  },
  {
    id: "v.uu",
    display: "อู",
    roman: "uu",
    length: "long",
    position: "below",
    example: { thai: "ปู", roman: "bpuu", en: "crab", emoji: "🦀" },
  },
  {
    id: "v.e",
    display: "เอะ",
    roman: "e",
    length: "short",
    position: "around",
    example: { thai: "เตะ", roman: "dtè", en: "kick", emoji: "⚽" },
  },
  {
    id: "v.ee",
    display: "เอ",
    roman: "ee",
    length: "long",
    position: "before",
    example: { thai: "เท", roman: "tee", en: "pour", emoji: "🫗" },
  },
  {
    id: "v.ae",
    display: "แอะ",
    roman: "ɛ",
    length: "short",
    position: "around",
    example: { thai: "แกะ", roman: "gɛ̀", en: "sheep", emoji: "🐑" },
  },
  {
    id: "v.aae",
    display: "แอ",
    roman: "ɛɛ",
    length: "long",
    position: "before",
    example: { thai: "แม่", roman: "mɛ̂ɛ", en: "mother", emoji: "👩‍👧" },
  },
  {
    id: "v.o",
    display: "โอะ",
    roman: "o",
    length: "short",
    position: "around",
    example: { thai: "โต๊ะ", roman: "dtó", en: "table", emoji: "🪑" },
  },
  {
    id: "v.oo",
    display: "โอ",
    roman: "oo",
    length: "long",
    position: "before",
    example: { thai: "โมง", roman: "moong", en: "o'clock", emoji: "🕐" },
  },
  {
    id: "v.aw",
    display: "เอาะ",
    roman: "ɔ",
    length: "short",
    position: "around",
    example: { thai: "เกาะ", roman: "gɔ̀", en: "island", emoji: "🏝️" },
  },
  {
    id: "v.aaw",
    display: "ออ",
    roman: "ɔɔ",
    length: "long",
    position: "after",
    example: { thai: "พ่อ", roman: "pɔ̂ɔ", en: "father", emoji: "👨‍👧" },
  },
  {
    id: "v.oe",
    display: "เออะ",
    roman: "ə",
    length: "short",
    position: "around",
    example: { thai: "เยอะ", roman: "yə́", en: "a lot", emoji: "💯" },
  },
  {
    id: "v.ooe",
    display: "เออ",
    roman: "əə",
    length: "long",
    position: "around",
    example: { thai: "เธอ", roman: "təə", en: "she, you (intimate)", emoji: "👧" },
  },
  {
    id: "v.ia",
    display: "เอีย",
    roman: "ia",
    length: "long",
    position: "around",
    example: { thai: "เมีย", roman: "mia", en: "wife (casual)", emoji: "👰" },
  },
  {
    id: "v.uea",
    display: "เอือ",
    roman: "ɯa",
    length: "long",
    position: "around",
    example: { thai: "เสือ", roman: "sɯ̌a", en: "tiger", emoji: "🐯" },
  },
  {
    id: "v.ua",
    display: "อัว",
    roman: "ua",
    length: "long",
    position: "around",
    example: { thai: "วัว", roman: "wua", en: "cow", emoji: "🐄" },
  },
  {
    id: "v.ai-m",
    display: "ใอ",
    roman: "ai",
    length: "short",
    position: "before",
    example: { thai: "ใจ", roman: "jai", en: "heart, mind", emoji: "💛" },
  },
  {
    id: "v.ai",
    display: "ไอ",
    roman: "ai",
    length: "short",
    position: "before",
    example: { thai: "ไป", roman: "bpai", en: "go", emoji: "🚶" },
  },
  {
    id: "v.ao",
    display: "เอา",
    roman: "ao",
    length: "short",
    position: "around",
    example: { thai: "เอา", roman: "ao", en: "take, want", emoji: "🤲" },
  },
  {
    id: "v.am",
    display: "อำ",
    roman: "am",
    length: "short",
    position: "after",
    example: { thai: "น้ำ", roman: "náam", en: "water", emoji: "💧" },
  },
]
